### ISSUE TITLE
Error when armature object and data block have different names

### ISSUE THREAD

**Issue by michaelday008** [chinedufn/landon#15]
if you have a model with an armature that is named something other than armature, the process will fail with the following message

```
Traceback (most recent call last):
  File "C:\Users\michael\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\convert-ik-to-fk.py", line 119, in execute
    for fkEditBone in bpy.data.armatures[fkArmature.name].edit_bones:
KeyError: 'bpy_prop_collection[key]: key "Armatue.001" not found'

location: <unknown location>:-1

location: <unknown location>:-1
```

### Reproduction Steps

Open up any mesh.  Ensure the armature is named something other than armature, like armatue.  F3 -> Convert...

The message above will happen.  The program actually successfully makes a copy of both the mesh and the armature, but then fails part way through.  In this case, the parent object was named Armatue, but the armature inside was name armature.  I think it assumed the object inside would have the same name as the parent.

**Comment by chinedufn** [comment]
Need to make sure that `Rename` and `Armature` in this screenshot both have the same name (So, change `Armature -> Rename`

The issue is that right now the script expects the armature data block to have the same name as the armature object.

![image](https://user-images.githubusercontent.com/2099811/92283152-49acf700-eecd-11ea-82c1-93ffdb5f81be.png)

---

## The Real Solution

Use the armature object's `.data` property to get the name of the armature data block. Then use that to look up the armature's data

So...

```
// Bad
bpy.data.armatures[fkArmature.name].edit_bones
```

Becomes

```
// Good
bpy.data.armatures[fkArmature.data.name].edit_bones
```

https://github.com/chinedufn/landon/blob/9cf1eb8b4130c4569f86d266c06145049576c10f/crates/iks-to-fks/convert-ik-to-fk.py#L119-L121

---

I'll leave this issue open until I get around to addressing the above.

Thanks for reporting! Let me know if you have any other issues.

**Comment by chinedufn** [comment]
`npm install -g blender-iks-to-fks@2.0.10` should no longer have this issue.
