### ISSUE TITLE
Open(Web)GL triangle face work flow?

### ISSUE THREAD

**Issue by kevzettler** [chinedufn/landon#24]
Hi Chinedu. 

I'm working to using Landon on a new WebGL project. I'm using `landon export` on my blend file. I'm then accessing the mesh data like:

```
const position = mesh.multi_indexed_vertex_attributes.positions.attribute.data;
const elements = mesh.multi_indexed_vertex_attributes.positions.indices
```

I'm using that data as a simplicial complex and rendering with regl. The mesh looked really messed up at render time.

![bad-waifu-triangles](https://user-images.githubusercontent.com/126209/142969519-2de09cd2-5103-4a34-a9f3-6c3c37f4291c.gif)

I dug into the exported JSON and noticed that it was export faces with variable sizes like:

```
"vertices_in_each_face": [
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            3,
```   

I then confirmed that my artist primarily works in quads in blender. WebGL doesn't support quad primitives. So I manually edited the blender file to convert all faces to tris and the rendering was corrected.

![waifu-triangles](https://user-images.githubusercontent.com/126209/142970265-01ce34bd-d332-48ea-862d-780d169de79a.gif)

I understand that Landon is staying unopinionated and pure to the data in blender I'm just wondering what you'd suggested for this workflow? how do you handle on Akigi asset pipeline?

**Comment by chinedufn** [comment]
Hey!

Yeah. A lot of the "what to do with exported data" workflow isn't well documented.

---

The `blender-mesh` API has a function to triangulate a mesh https://github.com/chinedufn/landon/blob/dc8c1dba7461b20ffb867b9e2cf06830cd3c5e26/blender-mesh/src/triangulate.rs#L3-L15



I export the data fairly raw at compile time using the API, then at runtime I call [`.combine_vertex_indices`](https://github.com/chinedufn/landon/blob/dc8c1dba7461b20ffb867b9e2cf06830cd3c5e26/blender-mesh/src/combine_indices/mod.rs#L232). 

`combine_vertex_indices()` currently also does triangulation while combining the indices into a single index buffer / performing any necessary vertex duplications. 
I wrote most of Landon's code when I was first learning Rust so things are a bit dense.

---

As for Akigi. 

I have a plugin based asset compilation system so there are different things in different places.. 

In my workflow I use the `landon` APIs, not the CLI.

At build time I more or less do

```rust
let blender_stdout = get_blender_data_from_files(vec![job.source_file().clone()]).unwrap();

let meshes = blender_mesh::parse_meshes_from_blender_stdout(&blender_stdout);

let out_dir = job.out_dir();

for (_filename, meshes) in meshes {
    for (mesh_name, mesh) in meshes {
        let mesh = MeshAsset::from(mesh);
        let mesh_bytes = (self.mesh_serializer)(mesh);

        let hash = hash_bytes_to_hex_non_cryptographic(mesh_bytes.as_slice());

        let mut out_mesh = std::fs::File::create(out_dir.join(&hash))?;
        out_mesh.write(mesh_bytes.as_ref())?;

        let asset_info = AssetMeta::new(hash.clone(), mesh_bytes.len() as _);
        std::fs::write(
            out_dir.join(format!("m-{}.meta", mesh_name)),
            &bincode::serialize(&asset_info).unwrap(),
        )
        .unwrap();
    }
}
```

And at runtime I more or less do:

```rust
// ... snippet from Akigi ...
mesh.y_up();

let bone_influences_per_vertex = mesh.armature_name().map(|_| 4);

let mut vertex_attribs = mesh.combine_vertex_indices(&CreateSingleIndexConfig {
    bone_influences_per_vertex,
    calculate_face_tangents: true,
});
vertex_attribs.face_weight_normals().unwrap();

    let indices = vertex_attribs.indices().clone();
    let vertices = vertex_attribs
        .vertices()
        .iter()
        .map(|v| {
            MeshVertexToBuffer::new(
                v.position(),
                v.normal().unwrap(),
                v.face_tangent().unwrap(),
                v.uv().unwrap(),
                v.bones().map(|b| {
                    let mut bone_indices = [0; 4];
                    let mut bone_weights = [0.; 4];

                    for (idx, b) in b.iter().enumerate() {
                        bone_indices[idx] = b.bone_idx();
                        bone_weights[idx] = b.weight();
                    }

                    BoneInfluencesToBuffer::new(bone_indices, bone_weights)
                }),
            )
        })
        .collect();

// ... snip ...
```

---

But I'm assuming that you're using the CLI, not the API.

So our options would be to either

1. Add some flags to the CLI to make it possible to transform your raw data at build time. I haven't yet thought about whether or not this is a good idea.

2. Expose `blender-mesh` to your code using `wasm-bindgen` so that you can use the libraries at runtime to transform your data. Perhaps by publishing it to `npm`.

3. Something else..? I haven't thought too deeply into this issue yet just trying to get you a quick response.

I'll pause there and see what you're thinking.

**Comment by kevzettler** [comment]
I'm thinking more of option 3. I think I could use the CLI in its current state and write a post processing script myself to massage the JSON. I'm just trying to understand what post-processing effort would be needed... Essentially, would have to reproduce the `combine_vertex_indices()` magic to create a single index buffer is that accurate?

Additionally @chinedufn, what are you thoughts on the UV workflow? I'm seeing similar problems with UVs and assuming there is some post processing massaging that needs to be done on them as well. I see there is a `uvs.indicies` and `uvs.attributes.data` but not sure what the `uvs.indicies` is and how it relates to the vertice positions index.

**Blender UVs**
![image](https://user-images.githubusercontent.com/126209/145746079-4dd159db-ef23-4442-9770-d43c2a77c77e.png)

**Landon export UVS**
![image](https://user-images.githubusercontent.com/126209/145746092-2b3404db-44b1-47a9-83cb-18f4e0381691.png)

**Comment by chinedufn** [comment]
Yeah the sounds accurate.

The combine vertex indices functions transforms UV data.

Basically the data comes out of Blender as a bunch of vertices, each of which has a position index, uv index and normal index.

These indices are used to find the corresponding position, uv and normal from the corresponding position, uv and normal arrays.

But ... in WebGL you have on set of vertex indices, not 3.

So you need your three data buffers (or one if you've combined all of your data into one buffer.. but either way it's 3 sets of data essentially) to be indexed using one set of indices.

So... to make that work some data needs to get duplicated such that vertex 75 has, say, index 123.. and index 123 points to the correct position, uv and normal.

Whereas before combining everything vertex 75 has index 123 for position, 255 for uv and 999 for normal (made up numbers).

I'm sure there are better explanations online.. but basically we're combining 3 index buffers into one.

**Comment by kevzettler** [comment]
Ok cool lots of good information here. I'm going to close this issue as theres lots of options. Thanks for your detailed replys and great support as always!

**Comment by chinedufn** [comment]
Awesome. Feel free to fire off questions whenever you like!
